FROM eclipse-temurin:21-jdk as build
WORKDIR /workspace/app

# コードとMavenビルドファイルをコピー
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

# Mavenでビルド
RUN ./mvnw install -DskipTests

# 実行用イメージ
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/app/target/*.jar app.jar

# エントリポイント（プレビュー機能を有効化）
ENTRYPOINT ["java", "--enable-preview", "-jar", "app.jar"]